package com.jamin.rescue.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.jamin.rescue.model.CrashModelGreen;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CRASH_MODEL_GREEN".
*/
public class CrashModelGreenDao extends AbstractDao<CrashModelGreen, Long> {

    public static final String TABLENAME = "CRASH_MODEL_GREEN";

    /**
     * Properties of entity CrashModelGreen.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Tag = new Property(1, String.class, "tag", false, "TAG");
        public final static Property Create_time = new Property(2, long.class, "create_time", false, "CREATE_TIME");
        public final static Property Message = new Property(3, String.class, "message", false, "MESSAGE");
    }


    public CrashModelGreenDao(DaoConfig config) {
        super(config);
    }
    
    public CrashModelGreenDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CRASH_MODEL_GREEN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"TAG\" TEXT," + // 1: tag
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 2: create_time
                "\"MESSAGE\" TEXT);"); // 3: message
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CRASH_MODEL_GREEN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CrashModelGreen entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(2, tag);
        }
        stmt.bindLong(3, entity.getCreate_time());
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(4, message);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CrashModelGreen entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(2, tag);
        }
        stmt.bindLong(3, entity.getCreate_time());
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(4, message);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public CrashModelGreen readEntity(Cursor cursor, int offset) {
        CrashModelGreen entity = new CrashModelGreen( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tag
            cursor.getLong(offset + 2), // create_time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // message
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CrashModelGreen entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTag(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreate_time(cursor.getLong(offset + 2));
        entity.setMessage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CrashModelGreen entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CrashModelGreen entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CrashModelGreen entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
